const tour1 = {
  id: 4,
  name: "Tuesday Tussle by CoinDCX",
  slug: "tuesday-tussle-by-coindcx",
  userTournaments: [
    {
      id: 45,
      totalCredits: 100000,
      availableCredits: 10111.398,
      userId: 18,
      userFullName: "Likhita Roy",
      profilePic: "sample",
      userOrders: [
        {
          id: 60,
          scriptName: "RELIANCE",
          quantity: 0,
          entryPrice: 2551.1516,
          orderType: "BUY",
        },
        {
          id: 116,
          scriptName: "AXISBANK",
          quantity: 0,
          entryPrice: 723.4,
          orderType: "BUY",
        },
        {
          id: 123,
          scriptName: "SUNPHARMA",
          quantity: 0,
          entryPrice: 836.8,
          orderType: "BUY",
        },
        {
          id: 237,
          scriptName: "INFY",
          quantity: 0,
          entryPrice: 1882.9,
          orderType: "BUY",
        },
        {
          id: 154,
          scriptName: "SBIN",
          quantity: 0,
          entryPrice: 513.1,
          orderType: "BUY",
        },
        {
          id: 168,
          scriptName: "NESTLEIND",
          quantity: 5,
          entryPrice: 19115.65,
          orderType: "BUY",
        },
        {
          id: 221,
          scriptName: "BHARTIARTL",
          quantity: 0,
          entryPrice: 707.85,
          orderType: "BUY",
        },
        {
          id: 105,
          scriptName: "TITAN",
          quantity: 0,
          entryPrice: 2600.0605,
          orderType: "BUY",
        },
        {
          id: 152,
          scriptName: "SBILIFE",
          quantity: 0,
          entryPrice: 1249.55,
          orderType: "BUY",
        },
        {
          id: 215,
          scriptName: "HDFC",
          quantity: 0,
          entryPrice: 2632.65,
          orderType: "BUY",
        },
        {
          id: 70,
          scriptName: "NIFTY 50",
          quantity: 0,
          entryPrice: 17950.9,
          orderType: "BUY",
        },
      ],
      score: 104796.398,
    },
    {
      id: 15,
      totalCredits: 100000,
      availableCredits: 1224.0312,
      userId: 24,
      userFullName: "Rishi",
      profilePic: "sample",
      userOrders: [
        {
          id: 147,
          scriptName: "SUNPHARMA",
          quantity: 0,
          entryPrice: 854.2,
          orderType: "BUY",
        },
        {
          id: 145,
          scriptName: "HDFCBANK",
          quantity: 0,
          entryPrice: 1538,
          orderType: "BUY",
        },
        {
          id: 150,
          scriptName: "ITC",
          quantity: 0,
          entryPrice: 223.35,
          orderType: "BUY",
        },
        {
          id: 153,
          scriptName: "IOC",
          quantity: 820,
          entryPrice: 123.55,
          orderType: "BUY",
        },
      ],
      score: 103806.0312,
    },
    {
      id: 32,
      totalCredits: 100000,
      availableCredits: 101202.25,
      userId: 41,
      userFullName: "VISHAL",
      profilePic: "sample",
      userOrders: [
        {
          id: 216,
          scriptName: "INFY",
          quantity: 0,
          entryPrice: 1925,
          orderType: "BUY",
        },
        {
          id: 80,
          scriptName: "AXISBANK",
          quantity: 0,
          entryPrice: 730.3,
          orderType: "BUY",
        },
        {
          id: 246,
          scriptName: "ASIANPAINT",
          quantity: 0,
          entryPrice: 3280,
          orderType: "BUY",
        },
        {
          id: 217,
          scriptName: "NESTLEIND",
          quantity: 0,
          entryPrice: 19425.1,
          orderType: "BUY",
        },
        {
          id: 132,
          scriptName: "HDFC",
          quantity: 0,
          entryPrice: 2615.95,
          orderType: "BUY",
        },
        {
          id: 249,
          scriptName: "BHARTIARTL",
          quantity: 0,
          entryPrice: 704.15,
          orderType: "BUY",
        },
        {
          id: 222,
          scriptName: "IOC",
          quantity: 0,
          entryPrice: 124.95,
          orderType: "BUY",
        },
        {
          id: 225,
          scriptName: "HDFCBANK",
          quantity: 0,
          entryPrice: 1517.85,
          orderType: "BUY",
        },
        {
          id: 170,
          scriptName: "SBILIFE",
          quantity: 0,
          entryPrice: 1248.8,
          orderType: "BUY",
        },
        {
          id: 218,
          scriptName: "POWERGRID",
          quantity: 0,
          entryPrice: 204.85,
          orderType: "BUY",
        },
        {
          id: 109,
          scriptName: "RELIANCE",
          quantity: 0,
          entryPrice: 2523.3,
          orderType: "BUY",
        },
        {
          id: 142,
          scriptName: "TITAN",
          quantity: 0,
          entryPrice: 2589.95,
          orderType: "BUY",
        },
        {
          id: 213,
          scriptName: "HINDUNILVR",
          quantity: 0,
          entryPrice: 2312.9,
          orderType: "BUY",
        },
        {
          id: 131,
          scriptName: "SBIN",
          quantity: 0,
          entryPrice: 513.75,
          orderType: "BUY",
        },
        {
          id: 201,
          scriptName: "ICICIBANK",
          quantity: 0,
          entryPrice: 808.6,
          orderType: "BUY",
        },
      ],
      score: 101202.25,
    },
    {
      id: 20,
      totalCredits: 100000,
      availableCredits: 3885,
      userId: 29,
      userFullName: "Nirav Nishit",
      profilePic: "sample",
      userOrders: [
        {
          id: 115,
          scriptName: "SBIN",
          quantity: 188,
          entryPrice: 511.25,
          orderType: "BUY",
        },
      ],
      score: 100855.4,
    },
    {
      id: 29,
      totalCredits: 100000,
      availableCredits: 100651.97,
      userId: 38,
      userFullName: "sTd.comedy influence",
      profilePic: "sample",
      userOrders: [
        {
          id: 79,
          scriptName: "SUNPHARMA",
          quantity: 0,
          entryPrice: 855.7,
          orderType: "BUY",
        },
        {
          id: 81,
          scriptName: "IOC",
          quantity: 0,
          entryPrice: 124.8,
          orderType: "BUY",
        },
        {
          id: 112,
          scriptName: "ICICIBANK",
          quantity: 0,
          entryPrice: 821.85,
          orderType: "BUY",
        },
        {
          id: 45,
          scriptName: "POWERGRID",
          quantity: 0,
          entryPrice: 205.95,
          orderType: "BUY",
        },
        {
          id: 110,
          scriptName: "AXISBANK",
          quantity: 0,
          entryPrice: 724.05,
          orderType: "BUY",
        },
        {
          id: 158,
          scriptName: "ASIANPAINT",
          quantity: 0,
          entryPrice: 3383.8,
          orderType: "BUY",
        },
        {
          id: 167,
          scriptName: "ITC",
          quantity: 0,
          entryPrice: 223,
          orderType: "BUY",
        },
        {
          id: 59,
          scriptName: "SBIN",
          quantity: 0,
          entryPrice: 514.65,
          orderType: "BUY",
        },
        {
          id: 58,
          scriptName: "HDFCBANK",
          quantity: 0,
          entryPrice: 1518.65,
          orderType: "BUY",
        },
        {
          id: 46,
          scriptName: "NIFTY 50",
          quantity: 0,
          entryPrice: 17941.75,
          orderType: "BUY",
        },
        {
          id: 253,
          scriptName: "HINDUNILVR",
          quantity: 0,
          entryPrice: 2308.45,
          orderType: "BUY",
        },
      ],
      score: 100651.97,
    },
    {
      id: 37,
      totalCredits: 100000,
      availableCredits: 9908.891,
      userId: 48,
      userFullName: "SHRIKARUNMATHESH",
      profilePic: "sample",
      userOrders: [
        {
          id: 227,
          scriptName: "SUNPHARMA",
          quantity: 0,
          entryPrice: 839.85,
          orderType: "BUY",
        },
        {
          id: 228,
          scriptName: "HDFC",
          quantity: 0,
          entryPrice: 2629.05,
          orderType: "BUY",
        },
        {
          id: 233,
          scriptName: "IOC",
          quantity: 0,
          entryPrice: 124.89297,
          orderType: "BUY",
        },
        {
          id: 248,
          scriptName: "SBIN",
          quantity: 0,
          entryPrice: 511.73798,
          orderType: "BUY",
        },
        {
          id: 226,
          scriptName: "AXISBANK",
          quantity: 0,
          entryPrice: 724.65,
          orderType: "BUY",
        },
        {
          id: 245,
          scriptName: "ITC",
          quantity: 0,
          entryPrice: 220.55,
          orderType: "BUY",
        },
        {
          id: 254,
          scriptName: "TITAN",
          quantity: 35,
          entryPrice: 2593.75,
          orderType: "BUY",
        },
      ],
      score: 100520.391,
    },
    {
      id: 23,
      totalCredits: 100000,
      availableCredits: 100160,
      userId: 32,
      userFullName: "Ansh Gupta ",
      profilePic: "sample",
      userOrders: [
        {
          id: 48,
          scriptName: "IOC",
          quantity: 0,
          entryPrice: 124.8,
          orderType: "BUY",
        },
      ],
      score: 100160,
    },
    {
      id: 39,
      totalCredits: 100000,
      availableCredits: 78214,
      userId: 49,
      userFullName: "Bhavesh",
      profilePic: "sample",
      userOrders: [
        {
          id: 129,
          scriptName: "AXISBANK",
          quantity: 30,
          entryPrice: 726.2,
          orderType: "BUY",
        },
      ],
      score: 100102,
    },
    {
      id: 52,
      totalCredits: 100000,
      availableCredits: 95042,
      userId: 60,
      userFullName: "Daksh Dutt",
      profilePic: "sample",
      userOrders: [
        {
          id: 165,
          scriptName: "IOC",
          quantity: 40,
          entryPrice: 123.95,
          orderType: "BUY",
        },
      ],
      score: 100046,
    },
    {
      id: 53,
      totalCredits: 100000,
      availableCredits: 93805.8,
      userId: 5,
      userFullName: "shubham rawal",
      profilePic:
        "file:///storage/emulated/0/Android/data/com.stockpemarket/files/Pictures/c41cf0fb-cd93-4051-8e20-1cf05e3ef398.jpg",
      userOrders: [
        {
          id: 219,
          scriptName: "SBIN",
          quantity: 4,
          entryPrice: 508.9,
          orderType: "BUY",
        },
        {
          id: 224,
          scriptName: "IOC",
          quantity: 5,
          entryPrice: 124.95,
          orderType: "BUY",
        },
        {
          id: 164,
          scriptName: "POWERGRID",
          quantity: 3,
          entryPrice: 205.95,
          orderType: "BUY",
        },
        {
          id: 220,
          scriptName: "AXISBANK",
          quantity: 4,
          entryPrice: 729,
          orderType: "BUY",
        },
      ],
      score: 100026.84999999999,
    },
    {
      id: 42,
      totalCredits: 100000,
      availableCredits: 1485.7031,
      userId: 52,
      userFullName: "PALLERLA PRANAV",
      profilePic: "sample",
      userOrders: [
        {
          id: 229,
          scriptName: "NIFTY 50",
          quantity: 5,
          entryPrice: 17991.4,
          orderType: "BUY",
        },
        {
          id: 77,
          scriptName: "HDFCBANK",
          quantity: 5,
          entryPrice: 1530.5,
          orderType: "BUY",
        },
        {
          id: 247,
          scriptName: "IOC",
          quantity: 10,
          entryPrice: 124.8,
          orderType: "BUY",
        },
        {
          id: 126,
          scriptName: "ICICIBANK",
          quantity: 0,
          entryPrice: 828.65,
          orderType: "BUY",
        },
        {
          id: 125,
          scriptName: "BHARTIARTL",
          quantity: 0,
          entryPrice: 720.8913,
          orderType: "BUY",
        },
        {
          id: 137,
          scriptName: "RELIANCE",
          quantity: 0,
          entryPrice: 2556.7,
          orderType: "BUY",
        },
        {
          id: 138,
          scriptName: "ITC",
          quantity: 0,
          entryPrice: 223.95,
          orderType: "BUY",
        },
        {
          id: 141,
          scriptName: "TITAN",
          quantity: 0,
          entryPrice: 2616,
          orderType: "BUY",
        },
        {
          id: 159,
          scriptName: "INFY",
          quantity: 0,
          entryPrice: 1921.7,
          orderType: "BUY",
        },
      ],
      score: 100020.9531,
    },
    {
      id: 50,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 2,
      userFullName: "Nidhi Singh",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 41,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 51,
      userFullName: "G",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 30,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 39,
      userFullName: "Mohan Rongala",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 33,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 43,
      userFullName: "Aritro Datta",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 59,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 66,
      userFullName: "Nish",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 60,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 67,
      userFullName: "Vinayak",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 18,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 27,
      userFullName: "Suman Kumar",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 36,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 47,
      userFullName: "Rohit Kumar",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
    {
      id: 22,
      totalCredits: 100000,
      availableCredits: 100000,
      userId: 31,
      userFullName: "Aniket Aryan",
      profilePic: "sample",
      userOrders: [],
      score: 100000,
    },
  ],
};

module.exports = { tour1 };
